### ISSUE TITLE
[META] Barcodes tested

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/barcodes#1]
This is to record which barcodes have been tested:

- [ ] C39        : CODE 39 - ANSI MH10.8M-1983 - USD-3 - 3 of 9
- [ ] C39+       : CODE 39 with checksum
- [ ] C39E       : CODE 39 EXTENDED
- [ ] C39E+      : CODE 39 EXTENDED + CHECKSUM
- [ ] C93        : CODE 93 - USS-93
- [ ] S25        : Standard 2 of 5
- [ ] S25+       : Standard 2 of 5 + CHECKSUM
- [ ] I25        : Interleaved 2 of 5
- [ ] I25+       : Interleaved 2 of 5 + CHECKSUM
- [x] C128       : CODE 128
- [ ] C128A      : CODE 128 A
- [ ] C128B      : CODE 128 B
- [ ] C128C      : CODE 128 C
- [ ] EAN2       : 2-Digits UPC-Based Extension
- [ ] EAN5       : 5-Digits UPC-Based Extension
- [ ] EAN8       : EAN 8
- [x] EAN13      : EAN 13 (includes ISBN - starts with either 978 or 979)
- [ ] UPCA       : UPC-A
- [ ] UPCE       : UPC-E
- [ ] MSI        : MSI (Variation of Plessey code)
- [ ] MSI+       : MSI + CHECKSUM (modulo 11)
- [ ] POSTNET    : POSTNET
- [ ] PLANET     : PLANET
- [ ] RMS4CC     : RMS4CC (Royal Mail 4-state Customer Code) - CBC (Customer Bar Code)
- [ ] KIX        : KIX (Klant index - Customer index)
- [ ] IMB        : IMB - Intelligent Mail Barcode - Onecode - USPS-B-3200
- [ ] IMBPRE     : IMB - Intelligent Mail Barcode - Onecode - USPS-B-3200- pre-processed
- [ ] CODABAR    : CODABAR
- [ ] CODE11     : CODE 11
- [ ] PHARMA     : PHARMACODE
- [ ] PHARMA2T   : PHARMACODE TWO-TRACKS
- [x] DATAMATRIX : DATAMATRIX (ISO/IEC 16022)
- [x] PDF417     : PDF417 (ISO/IEC 15438:2006)
- [x] QRCODE     : QR-CODE
- [ ] RAW        : 2D RAW MODE comma-separated rows
- [ ] RAW2       : 2D RAW MODE rows enclosed in square parentheses

Please log any that you've tested in the comments and I'll update.

**Comment by yorkshire-pudding** [comment]
RMS4CC doesn't appear to work with the example on the Wikipedia page. Needs further testing
